---
- fail: msg="hub_base_url is not defined"
  when: hub_base_url == ''
- fail: msg="nbgrader_user is not defined"
  when: nbgrader_user == ''
- fail: msg="nbgrader_root is not defined"
  when: nbgrader_root == ''

- name: clone the dockerfile git repository
  git: repo=https://github.com/compmodels/formgrader.git dest=/srv/formgrader

- name: get the user id of the nbgrader user
  script: get_user_id.sh {{ nbgrader_user }}
  register: nbgrader_user_id

- name: install bashrc for the nbgrader user
  template: src=bashrc.j2 dest=/home/{{ nbgrader_user }}/.bashrc owner={{ nbgrader_user }} group={{ nbgrader_user }}

- name: tweak ufw settings to allow connections to port 9000
  shell: ufw allow from 172.17.0.0/16 to {{ servicenet_ip }} port 9000

- name: tweak ufw settings to allow outgoing connections to port 5432
  shell: ufw allow from 172.17.0.0/16 to {{ ansible_ssh_host }} port 5432
