---
# Inventory file hostname of the NFS server (note this should be an Ansible
# alias, not the real hostname)
nfsserver: ''
# Path to mount NFS on the clients
nfsmount: ''
# Domain for idmapd
nfsdomain: ''
# Options to mount NFS with
nfsoptions: rw