---
- fail: msg="no ssh keys defined"
  when: github_usernames == [] and other_ssh_keys == []

- name: sshd configuration
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode=0644
  sudo: yes
  notify:
  - restart sshd

- name: directory to hold public keys
  file: state=directory path=/tmp/pubkeys mode=0755

- name: fetch public keys from github
  get_url: dest=/tmp/pubkeys/{{ item }}-pubkeys url=https://github.com/{{ item }}.keys force=yes
  with_items: github_usernames

- name: include additional public keys
  template: dest=/tmp/pubkeys/other-pubkeys src=other-pubkeys.j2

- name: assemble the authorized keys file
  assemble: dest=/root/.ssh/authorized_keys mode=0600 src=/tmp/pubkeys
  sudo: yes
