---
# This is the directory to install the backup scripts to
backup_script_directory: /srv/backup

# This is the directory you actually want to back up
backup_source_directory: ''

# This is the name of the CloudFiles container where the backups will be stored
backup_container: ''

# This is the GPG key id and password for the Duplicity backups. In general you
# should NEVER override this here -- override it in a vault file that is
# encrypted.
gpg_key: ''
gpg_pass: ''

# As with the GPG key, never actually include your Rackspace username and API
# key here -- they should be overwritten in an encrypted vault file.
rackspace_username: ''
rackspace_api_key: ''
